version: '3.1'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: notes
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
